[project]
name = "punching-face"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true
required-version = '26.5.1'
force-exclude = '/(node_modules|\.local|\.venv|public|dist|dist-guest|artifacts|target)/'
